// 389. Find the Difference.java

// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

 

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"
 

// Constraints:

// 0 <= s.length <= 1000
// t.length == s.length + 1
// s and t consist of lowercase English letters.



class Solution {
    public char findTheDifference(String s, String t) {
    int x=0;
    for(char i:s.toCharArray()){
        x^=i;
    }
    for(char i:t.toCharArray()){
        x^=i;
    }
    return (char)x;
    }
}

// Accepted
// SENTHIL
// SENTHIL
// submitted at Feb 02, 2024 21:30

// Editorial

// Solution
// Runtime
// 1
// ms
// Beats
// 100.00%
// of users with Java
// Memory
// 42.01
// MB
// Beats
// 15.92%
// of users with Java
